---

#
# This file is part of the `src-run/rf-docker` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
#

dist: trusty
sudo: required

git:
  depth: 3

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.8.1

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v
  - docker -v
  # symfony application folder
  - mkdir symfony
  - cp .env.dist .env
  - cat docker-compose.yml

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps

...
